### ISSUE TITLE
Make schema errors more explicit by indicating missing/wrong property

### ISSUE THREAD

**Issue by sushi2all** [pdfme/pdfme#268]
### Is your feature request related to a problem? Please describe.

I'm trying to debug an `Invalid argument` error. The console reports the field that have issues, but doesn't say what issue they have.

This is especially annoying after manually checking that the passed object apparently corresponds to the type specification in the docs.

### Describe the solution you'd like

Now:
```console
ERROR POSITION: template.schemas.0.field1
ERROR MESSAGE: Invalid input
```

Would like:
```console
ERROR POSITION: template.schemas.0.field1
ERROR MESSAGE: Missing required property X | Wrong type for property X (<wrong type>), should be  <right type>
```

### Describe alternatives you've considered

Magic crystal ball? But haven't found one 😉

### Additional context

This is the error

```console
helper.js:61 Uncaught Error: Invalid argument:
--------------------------
ERROR POSITION: template.schemas.0.field1
ERROR MESSAGE: Invalid input
--------------------------
ERROR POSITION: template.schemas.0.field2
ERROR MESSAGE: Invalid input
--------------------------
    at kA (helper.js:61:19)
    at MA (helper.js:76:39)
    at new nd (class.ts:80:5)
    at new ix (Designer.tsx:15:5)
    at Proxy.initDesigner (PrintTemplateDesigner.vue?t=1695050813555:89:23)
```

This is the template I'm passing to the Designer constructor:
```json
{
  "basePdf": "...",
  "columns":
  [
    "field1",
    "field2"
  ],
  "sampledata":
  [
    {
      "field1": "text",
      "field2": "text"
    }
  ],
  "schemas":
  [
    {
      "field1": {
        "alignment": "left",
        "backgroundColor": null,
        "characterSpacing": 0,
        "dynamicFontSize": null,
        "fontColor": null,
        "fontName": "Roboto",
        "fontSize": 13,
        "height": 7,
        "lineHeight": 1,
        "position": {
          "x": 32.54,
          "y": 53.71
        },
        "rotate": null,
        "type": "text",
        "verticalAlignment": null,
        "width": 154.06
      },
      "field2": {
        "alignment": "left",
        "backgroundColor": null,
        "characterSpacing": 0,
        "dynamicFontSize": null,
        "fontColor": null,
        "fontName": "Roboto",
        "fontSize": 13,
        "height": 7,
        "lineHeight": 1,
        "position": {
          "x": 86.52,
          "y": 110.6
        },
        "rotate": null,
        "type": "text",
        "verticalAlignment": null,
        "width": 35
      }
    }
  ]
}
```

**Comment by sushi2all** [comment]
Found the solution to the specific error: the validation doesn't accept `null` values.

In this case a more explicit error line could be:

```console
ERROR POSITION: template.schemas.0.field1.rotation
ERROR MESSAGE: null value not allowed
```

Still, as I suggest in #275, null values should simply be ignored.

**Comment by hand-dot** [comment]
ref: https://github.com/pdfme/pdfme/issues/275#issuecomment-1734678401
