### ISSUE TITLE
An error occurs if a value is not set for the image schema.

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#498]
### Describe the bug

In other words, it fails with undefined. An empty string is OK.

```js
const inputs = [{
  image: undefined // ERROR
 //  image: "" // OK
 //  image: "data:image/png;base64,iVBORw0", // OK
}];
```

### To Reproduce

```tsx
const { generate } = require('@pdfme/generator');
const { text, image } = require('@pdfme/schemas');
const fs = require('fs');
const path = require('path');

const template = {
  "basePdf": { "width": 210, "height": 297, "padding": [0, 0, 0, 0] },
  schemas: [
    {
      text: {
        type: 'text',
        position: { x: 0, y: 0 },
        width: 10,
        height: 10,
      },
      image: {
        type: 'image',
        position: { x: 20, y: 20 },
        width: 10,
        height: 10,
      },
    },
  ],
};

const inputs = [{
  text: 'a',
  // image: "" OK
  // image: "data:image/png;base64,iVBORw0KGgo...", OK
}];

generate({
  template, inputs, plugins: { text, image }
}).then((pdf) => {
  console.log(pdf);
  fs.writeFileSync(path.join(__dirname, `test.pdf`), pdf);
});
```

### Expected behavior

No error

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): schemas
- pdfme version: latest
- Operating system: mac
- Node.js version or Browser name & version: latest chrome
```

### Your Error Log

```shell
node generate.js
/pdfme/packages/schemas/dist/cjs/src/graphics/pdfHelper.js:6
    return content.startsWith('data:application/pdf;');
                   ^

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at isPdf (/pdfme/packages/schemas/dist/cjs/src/graphics/pdfHelper.js:6:20)
    at pdf (/pdfme/packages/schemas/dist/cjs/src/graphics/image.js:15:55)
    at generate (/pdfme/packages/generator/dist/cjs/src/generate.js:76:23)

Node.js v20.10.0
```

**Comment by hand-dot** [comment]
ref: https://github.com/pdfme/pdfme/issues/412

**Comment by peteward** [comment]
I can have a look at this tomorrow
