### ISSUE TITLE
[@pdfme/schema/table] Custom PDF is not supported

### ISSUE THREAD

**Issue by Zego92** [pdfme/pdfme#545]
### Describe the bug

In my code I am trying to generate a table or tables inside a PDF document.
In this case I just use the data I find in the [official documentation](https://pdfme.com/docs/tables).
The stack trace for this error
`Error: [@pdfme/schema/table] Custom PDF is not supported
    at createSingleTable (/Users/eugene/Documents/ngft-print-nestjs/node_modules/@pdfme/schemas/src/tables/tableHelper.ts:273:35)
    at pdfRender (/Users/eugene/Documents/ngft-print-nestjs/node_modules/@pdfme/schemas/src/tables/pdfRender.ts:115:40)
    at generate (/Users/eugene/Documents/ngft-print-nestjs/node_modules/@pdfme/generator/src/generate.ts:59:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
`

### To Reproduce

Install 
`@pdfme/common`
`@pdfme/generator`
`@pdfme/pdf-lib`
`@pdfme/schemas`
`@pdfme/ui`

Get the plain code from [official documentation](https://pdfme.com/docs/tables).
Create a business logic that provides a generating pdf file (see official documentation)

### Expected behavior

Creating a PDF file that contains one or more tables

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): @pdfme/generator, @pdfme/schemas, @pdfme/pdf-lib, @pdfme/common
- pdfme version: 4.2.4
- Operating system: MacOS 14.5 (23F79)
- Node.js version or Browser name & version: Node 22.4.0, Google Chrome 126.0.6478.185
```

### Your Error Log

```shell
Error: [@pdfme/schema/table] Custom PDF is not supported
    at createSingleTable (/Users/eugene/Documents/ngft-print-nestjs/node_modules/@pdfme/schemas/src/tables/tableHelper.ts:273:35)
    at pdfRender (/Users/eugene/Documents/ngft-print-nestjs/node_modules/@pdfme/schemas/src/tables/pdfRender.ts:115:40)
    at generate (/Users/eugene/Documents/ngft-print-nestjs/node_modules/@pdfme/generator/src/generate.ts:59:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by hand-dot** [comment]
Hey @Zego92 ,
We know about this problem. I will handle in bellow issue.
https://github.com/pdfme/pdfme/issues/486#issuecomment-2234988858
