### ISSUE TITLE
Designer cannot load PDFs in array/buffer

### ISSUE THREAD

**Issue by PlanetTeamSpeakk** [pdfme/pdfme#630]
### Describe the bug

When attempting to load a template with a base PDF in the form of a Uint8Array or ArrayBuffer, pdfme seems to wrongly think this is a base64 string and will attempt to parse it as such resulting in an error saying `<some minified name>.split is not a function` (full error below). Only solution is to convert the data into a base64 string.

### To Reproduce

I am using the following function to load the template:
```js
  function loadBasePDF(e: Event) {
    const file = (e.target! as HTMLInputElement).files![0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = () => {
      const a = new Uint8Array(reader.result as ArrayBuffer);
      // Not including the next line and instead passing the array directly (either as an array or a buffer)
      // will result in the attached error. Converting it to base64 first solves this issue.
      // Obviously, loading the data directly as base64 using readAsDataURL works too.
      const b64 = 'data:application/pdf;base64,' + btoa([...a].map(b => String.fromCharCode(b)).join(''));
      designer.value?.updateTemplate({
        basePdf: b64,
        schemas: [],
      })
    };
    reader.readAsArrayBuffer(file);
  }
  ```

### Expected behavior

PDFMe should be able to parse PDFs in Uint8Array or ArrayBuffer form as well, but it can only parse base64 without errors.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): @pdfme/ui
- pdfme version: 5.2.1
- Operating system: Windows
- Browser name & version: Edge 131.0.2903.36
```

### Your Error Log

```shell
Uncaught (in promise) TypeError: e10.split is not a function
    at kj (index.es.js:9008:15)
    at Lue (index.es.js:26766:13)
    at Nue (index.es.js:26781:33)
    at async index.es.js:130089:15

Which happens on this line:
const t = e.split(";base64,")[1] ? e.split(";base64,")[1] : e, r = Z2e(t), n = new Uint8Array(r.length);
```

**Comment by hand-dot** [comment]
I was handled by @necessarylion .
Released as 5.2.11
