### ISSUE TITLE
Error while requiring module [object Object]

### ISSUE THREAD

**Issue by AndresEV22** [pdfme/pdfme#655]
### Describe the bug

Hi!, i'm trying to use the library with Nuxt3 based on TypeScript, but when i install the library on the NuxtConfig file in modules section i'm getting the following error:` | "Error while requiring module [object Object]: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './module' is not defined by 'exports'" | `and the app don't starts. In another way, if i don't put the library in the modules section from NuxtConfig file when i recharge the page i get another error : `"Cannot find module './swap' Require stack"`

### To Reproduce

In the first error my NuxtConfig is: 

```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      backendUrl: "",
      ssoApiUrl: "",
      baseFrontendUrl: "",
      appVersion: "",
      debugToken: "",
      currentCompany: "LCH",
      cobolqlUrl: "",
    },
  },
  devtools: { enabled: true },
  css: [
    "~/assets/css/main.css",
    "vue-toastification/dist/index.css",
    "@mdi/font/css/materialdesignicons.min.css",
  ],
  build: {
    transpile: ["vue-toastification"],
  },
  modules: ["@pdfme/generator"],
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
});
```
and in the second error i'm just using the generate function

### Expected behavior

Just the app stability

### Your Environment

```markdown
- pdfme package(@pdfme/generator @pdfme/common @pdfme/schemas):
- pdfme version: 5.2.10
- Operating system: Arch Linux
- Node.js version or Browser name & version: 23.3.0
- Nuxt version: 3.11.2
- Vue version: 3.4.21
```

### Your Error Log

```shell
First Error:

[3:50:46 p. m.]  ERROR  Error while requiring module [object Object]: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './module' is not defined by "exports" in /home/../../../../frontend/node_modules/@pdfme/generator/package.json


[3:50:46 p. m.]  ERROR  Cannot start nuxt:  Package subpath './module' is not defined by "exports" in /../../../../../frontend/node_modules/@pdfme/generator/package.json

  at exportsNotFound (node:internal/modules/esm/resolve:314:10)
  at packageExportsResolve (node:internal/modules/esm/resolve:661:9)
  at resolveExports (node:internal/modules/cjs/loader:638:36)
  at Function._findPath (node:internal/modules/cjs/loader:737:31)
  at Function._resolveFilename (node:internal/modules/cjs/loader:1225:27)
  at Function.resolve (node:internal/modules/helpers:146:19)
  at Function._resolve [as resolve] (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:241814)
  at resolveModule (node_modules/.pnpm/@nuxt+kit@3.12.4_magicast@0.3.4_rollup@4.19.1/node_modules/@nuxt/kit/dist/index.mjs:2224:29)
  at requireModule (node_modules/.pnpm/@nuxt+kit@3.12.4_magicast@0.3.4_rollup@4.19.1/node_modules/@nuxt/kit/dist/index.mjs:2229:24)
  at loadNuxtModuleInstance (node_modules/.pnpm/@nuxt+kit@3.12.4_magicast@0.3.4_rollup@4.19.1/node_modules/@nuxt/kit/dist/index.mjs:2508:92)
```

Second error: 
```
 ERROR  Cannot find module './swap'
Require stack:
- /home/../../../../frontend/unicode-trie

  Require stack:
  - unicode-trie
  at Function._resolveFilename (node:internal/modules/cjs/loader:1239:15)
  at Function._load (node:internal/modules/cjs/loader:1064:27)
  at TracingChannel.traceSync (node:diagnostics_channel:322:14)
  at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
  at Module.require (node:internal/modules/cjs/loader:1325:12)
  at require (node:internal/modules/helpers:136:16)
  at unicode-trie:2:22
  at ViteNodeRunner.runModule (node_modules/.pnpm/vite-node@2.0.4_@types+node@22.0.0_terser@5.31.3/node_modules/vite-node/dist/client.mjs:399:11)
  at ViteNodeRunner.directRequest (node_modules/.pnpm/vite-node@2.0.4_@types+node@22.0.0_terser@5.31.3/node_modules/vite-node/dist/client.mjs:381:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```
```


### Additional context

_No response_

**Comment by Zielgestalt** [comment]
This is not a Nuxt module, so you can’t add it to the Nuxt config like that. But you can simply import pdfme in your components or e.g. server routes and use it there. I usually use it in a server route and start with:

`import { type Template, type Font } from '@pdfme/common'
import { text, image, table, line, rectangle } from '@pdfme/schemas'
import { generate } from '@pdfme/generator'

export default defineEventHandler(async (event) => {
  ...
  return pdfDocument
})`

**Comment by hand-dot** [comment]
Closing as answered. pdfme packages are libraries, not Nuxt modules, so they should not be added to the Nuxt modules array. Import @pdfme/generator, @pdfme/common, and schemas from application code or server routes instead.
