### ISSUE TITLE
PDF generation error

### ISSUE THREAD

**Issue by mbiegert** [pdfme/pdfme#78]
Hello, we have hit an issue today with generating pdfs with custom fonts.

We use the latest @pdfme/generator and @pdfme/common (both v1.0.14).
It appears it cannot locate the correct font to use for a text entry:
```
webpack://pdfme/generator/src/helper.ts:296
        fontValue.widthOfTextAtSize(testString, size) + (testString.length - 1) * characterSpacing;
                  ^

TypeError: Cannot read properties of undefined (reading 'widthOfTextAtSize')
    at testString (webpack://pdfme/generator/src/helper.ts:296:19)
    at getOverPosition (webpack://pdfme/generator/src/helper.ts:217:9)
    at getSplitPosition (webpack://pdfme/generator/src/helper.ts:230:19)
    at getSplittedLines (webpack://pdfme/generator/src/helper.ts:250:20)
    at null.<anonymous> (webpack://pdfme/generator/src/helper.ts:304:26)
    at Array.forEach (<anonymous>)
    at arg (webpack://pdfme/generator/src/helper.ts:293:30)
    at null.<anonymous> (webpack://pdfme/generator/src/helper.ts:404:5)
    at Generator.next (<anonymous>)
    at null.<anonymous> (webpack://pdfme/node_modules/@pdf-lib/fontkit/dist/fontkit.es.js:36550:1)
    at new Promise (<anonymous>)
    at null.aQ (webpack://pdfme/node_modules/@pdf-lib/fontkit/dist/fontkit.es.js:36550:1)
    at arg (webpack://pdfme/generator/src/helper.ts:399:7)
    at null.<anonymous> (webpack://pdfme/generator/src/generate.ts:69:15)
    at Generator.next (<anonymous>)
    at null.o (webpack://pdfme/generator/src/constants.ts:1:26)
```

The font object passed to the `generate` function as logged in the line before passing it in:
```
Creating pdf with font option {
  futuraBook: {
    data: <Buffer c6 ec ... many more bytes>,
    fallback: true,
    subset: false
  },
  futuraDemi: {
    data: <Buffer bf a9 ... many more bytes>,
    subset: false
  }
}
```

The schema has text entries with `fontName` set to "futuraDemi" and other text entries with no `fontName` set. I'm currently investigating the issue in the pdfme code, maybe it has something to do with the determination of the fallback font name?

**Comment by mbiegert** [comment]
Alright, please excuse this noise, I've just looked at it again and found out that we were passing the font object wrong, instead of
```
generate({ template, inputs, options: { font: options.font }});
```
we were passing in
```
generate({ template, inputs, options: options.font });
```
which typescript unfortunately did not catch because it only know that `options.font` was of the `Font` type which only has an index signature and therefore suits the `options` object as well.

Anyway this can be closed as not an issue, however the issue was a bit cumbersome to track down. Maybe it's possible to add a check for existing font names to the "checkGenerateProps()" call? In order to make sure that all fontNames required by the schema are actually available.

**Comment by hand-dot** [comment]
@mbiegert 
Thank you for reporting
Maybe, in this case,  you should use `checkFont`.

I'll close this issue.

**Comment by mbiegert** [comment]
Thanks for checking in, I've just encountered another issue stemming from the switch from labelmake to pdfme:
```
webpack://pdfme/generator/src/generate.ts:63
        const schema = schemas[j];
                               ^

TypeError: Cannot read properties of undefined (reading 'myInputFieldOne')
    at null.<anonymous> (webpack://pdfme/generator/src/generate.ts:63:32)
    at Generator.next (<anonymous>)
    at null.o (webpack://pdfme/generator/src/constants.ts:1:26)
```

This rather cryptic error results from the basePDF having more pages than the schemas array has entries. First I couldn't find it in the documentation that that is a requirement now and second a more telling error message would also have been very helpful. If I get some time I might be able to implement some additional checks in the beginning of the `generate` function.

**Comment by hand-dot** [comment]
@mbiegert 
>  First I couldn't find it in the documentation that that is a requirement now and second a more telling error message would also have been very helpful. 
Indeed, the error message is not good...

> If I get some time I might be able to implement some additional checks in the beginning of the generate function.
Good! if you contribute to pdfme , I'll be glad!
